# We first turn off the monitor
listener {
    timeout = 400
    on-timeout = hyprctl dispatch dpms off # Turn off monitor
    on-resume = hyprctl dispatch dpms on # Turn on when back
}
# Then we lock it after enough time
listener {
    timeout = 1000
    on-timeout = hyprlock
}
