[appearance]
background_color = "#{background.strip}"
text_color = "#{foreground.strip}"
input_background_color = "#{color1.strip}"
input_text_color = "#{foreground.strip}"
list_background_color = "#{background.strip}"
selected_background_color = "#{color1.strip}"
selected_text_color = "#{background.strip}"
border_color = "#{color2.strip}"
