background = 0xFF{background.strip}
base = 0xFF{color0.strip}
text = 0xFF{foreground.strip}
alternate_base = 0xFF{color8.strip}
bright_text = 0xFF{color15.strip}
accent = 0xFF{color1.strip}
accent_secondary = 0xFF{color2.strip}
